### ISSUE TITLE
Don't load tabs until selected doesn't work in incognito.

### ISSUE THREAD

**Issue by jtagcat** [htrinter/Open-Multiple-URLs#17]
Branched this issue from #16 
@fakhamatia `Don't load tabs until selected` are you using Firefox or Chrome?

The way it's currently implemented is so the extension keeps compatibility with Chrome and consequently does not work with incognito. If you are using Firefox, this could potentially be fixed by using the newer Firefox-only UI, when using Firefox (detect automatically, may get weirded out by user-agent extensions, not sure) or set in settings.

**Comment by fakhamatia** [comment]
Chrome 81.0.4044.92

**Comment by jtagcat** [comment]
Yup can't do anything about it, closing as wontfix.
