### ISSUE TITLE
[Feature request] Enable calls passing with POST parameters

### ISSUE THREAD

**Issue by joanaranda** [htrinter/Open-Multiple-URLs#19]
This extension is great. However, I am currently facing a use case that the tool does not support, and it would be wonderful if it could be added.
Regularly, I need to check if several IPs are blacklisted according to https://www.ipvoid.com/ip-blacklist-check/ . I would like to check them in blocks of 10 or 20, but the issue is that IP is not passed as a visible argument (GET parameter), but as a POST parameter (i.e. not included in the URL).
I think adding that feature would add a lot of new usage opportunities for other users like me. POST passing parameters is something quite usual, and having to deal with techical tools like Postman is out of the scope for many regular users. label:feature

**Comment by htrinter** [comment]
> having to deal with techical tools like Postman is out of the scope for many regular users

That is probably true, although I think it is in scope for users that know the distinctions between HTTP request methods. Which they would have to know about to use the proposed feature. I think a REST client is a better fit for the use case.
