### ISSUE TITLE
Some feature to better

### ISSUE THREAD

**Issue by dnknn** [htrinter/Open-Multiple-URLs#20]
Hi:)    Can support these functions ❓

- ## 🕗 Delay open
> At the same time, the same domain will be judged as malicious by the server.

- ## 🔢 How many URLs can be opened at a time.

Multi-links   https://chrome.google.com/webstore/detail/gflgnmgilmokfhbckilljalhemjjeldl
Multiple URL Opener   https://chrome.google.com/webstore/detail/lompiehpjobkhelnjlhjiedhddijiekg

<details>

<summary>Click to expand to view the sample image </summary>

![0628101714](https://user-images.githubusercontent.com/10995302/85936659-59d5b280-b92f-11ea-8c37-9cf627555425.png)
![0628102247](https://user-images.githubusercontent.com/10995302/85936660-5b06df80-b92f-11ea-845e-2004efd19466.png)

![URL dely](https://user-images.githubusercontent.com/10995302/85936151-57bd2500-b92a-11ea-96a7-3cd106ab5283.gif)

</details>

----
- ## 👥 URL-Group function
> You can open all URLs under this group with one click

URL Group Manager    https://chrome.google.com/webstore/detail/dpaoeoomjbnkcognlcnlflilidjdlmoi
<details>
<summary>Click to expand to view the sample image</summary>

![0628111408](https://user-images.githubusercontent.com/10995302/85936797-7f16f080-b930-11ea-9f4e-eb67f8516f05.png)

</details>

---
- ## 🎁 Extra feature gift
 Enter the head and tail serial number, to auto open the continuous page. E.g 👇
```
https://xxx.com/page/3
https://xxx.com/page/4
https://xxx.com/page/5
···············
https://xxx.com/page/15
```

Tab Opener	https://chrome.google.com/webstore/detail/hgamfdaglcaalcokanmikkcipmlibben

<details>
<summary>Click to expand to view the sample image</summary>

![0628113507](https://user-images.githubusercontent.com/10995302/85937156-7378f900-b933-11ea-9a9a-e169cb6cd176.png)

</details>

**Comment by jtagcat** [comment]
Please open one issue per issue.

> Delay open

Duplicate of #18 

> How many URLs can be opened at a time.

Insert x numbers of links at a time or use the mentioned extensions, it's too much work to implement. 

> URL-Group function

Out of scope of this extension. You may use bookmark folders instead, built in to all popular browsers, including Chrome.

> ~Extra feature gift~ URLs with wildcards

Ok idea, but low priority. It's easily possible to make a list with a wide range of tools. For example:
 - Bash:
```
$ echo foo.bar/page/{1..5} | tr " " "\n"
foo.bar/page/1
foo.bar/page/2
foo.bar/page/3
foo.bar/page/4
foo.bar/page/5
```
 - LibreOffice Calc / MS Office Excel / Google Sheets:
![1](https://user-images.githubusercontent.com/38327267/85978242-dcad4a80-b9cd-11ea-9917-4cdaa4e51f52.png)
![image](https://user-images.githubusercontent.com/38327267/85978254-e33bc200-b9cd-11ea-81f0-2281853dc92c.png)

**Comment by dnknn** [comment]
Thank you for your response, hope this extension will be better. 
Good Luck!
