### ISSUE TITLE
URL RegExp is bad, refactor it 🐞

### ISSUE THREAD

**Issue by dnknn** [htrinter/Open-Multiple-URLs#21]
```
^https?:\/\/.+^https?:\/\/.*
user-select:none的CSS元素 要手放大 d 
df 个https://Google.com dng...哈哈
```

`user-select:none的CSS元素`   Extracted as a URL link 🐞

Preview
<details>
<summary>see 🎬gif</summary>

![Error extraction](https://user-images.githubusercontent.com/10995302/87883731-ea3d7980-ca3b-11ea-8d96-eb3b4d840c4b.gif)

</details>

Optimize and improve the regular extraction rules

---

`/*https://google.com/*/`
Error extract 👇
`https://google.com/*/`

URL cannot have an `✱` asterisk

<details>
<summary>see 🎬gif</summary>

![Error extraction2](https://user-images.githubusercontent.com/10995302/87883850-d47c8400-ca3c-11ea-956b-aa13707e3d99.gif)

</details>

----
I found that URL extract of `Open-Multiple-URLs`  is very bad, 
You can experience and test the following extension, which is perfect and never goes wrong.

- ☂`Copy All Urls` &emsp;&emsp;(more than copy, the most powerful thing is to intelligently open the URL in the clipboard)
https://chrome.google.com/webstore/detail/djdmadneanknadilpjiknlnanaolmbfk
https://github.com/vincepare/CopyAllUrl_Chrome

It can intelligently open multiple URLs in the clipboard,
Improve it 👇

/https?:\/\/[\w-]+\.[a-z0-9\/:%_+.,#?!@&=-]+/gi
<details>
<summary>First set option⚙</summary>

![0713030958](https://user-images.githubusercontent.com/10995302/87256548-46e1e700-c4c6-11ea-9c27-678bdaf30a97.png) 
![0713031135](https://user-images.githubusercontent.com/10995302/87256551-49dcd780-c4c6-11ea-9305-16a51b16e8da.png)

</details>

<details>
<summary>Please note that the shortcut key I set is <kbd>Alt+V </kbd> ,than see gif demo</summary>
&emsp;

![smartpaste](https://user-images.githubusercontent.com/10995302/87256584-94f6ea80-c4c6-11ea-903d-ab2f761ba427.gif)

</details>

----

From the source code of `Copy All Urls`, it can be found that this RegExp is perfect, 
## `/https?:\/\/[a-z0-9\/:%_+.,#?!@&=-]+/gi`

https://github.com/vincepare/CopyAllUrl_Chrom## `/https?:\/\/[a-z0-9\/:%_+.,#?!@&=-]+/gi`e/blob/7bad72b032f3fb36c6ad970e1448674f1ba77644/background.js#L120
![0720044213](https://user-images.githubusercontent.com/10995302/87884808-6e472f80-ca43-11ea-81b4-6cb8f50e5459.png)

### https://regex101.com/r/ZSywXB/1

<details>
<summary>Screenshot</summary>

![0720044627](https://user-images.githubusercontent.com/10995302/87884946-7b185300-ca44-11ea-8d06-6bcb483ced76.png)

</details>

### [https://uzitech.github.io/regexper](https://uzitech.github.io/regexper/#%7Cflavor%3Djavascript%7C%2F%28https%3F%7Cftp%7Cssh%7Cmailto%29%3A%5C%2F%5C%2F%5Ba-z0-9%5C%2F%3A%25_%2B.%2C%23%3F!%40%26%3D-%5D%2B%2Fgi)

<details>
<summary>Screenshot</summary>

![0720044931](https://user-images.githubusercontent.com/10995302/87884942-7358ae80-ca44-11ea-8874-61d5bee938c2.png)

</details>

---
Back to `Open-Multiple-URLs` ,  Why is there such a long and complicated URL regular?

https://github.com/htrinter/Open-Multiple-URLs/blob/a479cd88522b90f4e4bfb39df066548c16bb22d3/popup.js#L131

You can click to view to reproduce 👇
## https://regex101.com/r/fxhzPz/1

![0720102530](https://user-images.githubusercontent.com/10995302/87893748-5be4ea00-ca73-11ea-9fd1-003562c4386d.png)

Therefore, it is recommended to change the URL regularity to
### `/https?:\/\/[a-z0-9\/:%_+.,#?!@&=-]+/gi` 

Because it is perfect, only Imperfect place 👇
![0720122711](https://user-images.githubusercontent.com/10995302/87899674-80958d80-ca84-11ea-8955-f76db5a4c38f.png)

---
### **Update**: You may also need to add the `~` symbol,
`https://en.wikipedia.org/wiki/Rickrolling#:~:text=New%20York`

because🆕 URL-API  `#:~:text=` see more 📜👇

https://developers.google.com/web/updates/2020/02/nic80?hl=tr#more
https://github.com/WICG/scroll-to-text-fragment
https://chromestatus.com/feature/4733392803332096

Improve it 👇

**Comment by jtagcat** [comment]
Hi, could you please make a PR of your reccommended changes?

**Comment by dnknn** [comment]
> Hi, could you please make a PR of your reccommended changes?

You refresh again please, because I just re-edited and updated this issues, It is more readable.

No, no, I don't understand PR at all, because I am not a developer, 
I only know how to browse 🐈github, and I don't understand code-related operations at all.

**Comment by jtagcat** [comment]
Hey, maybe you are interested in closing this issue as part of https://hacktoberfest.digitalocean.com ?

The accompanying videos there introduce git and/or GitHub quite nicely.
