### ISSUE TITLE
[Feature Request] Add Total Number of URL's 

### ISSUE THREAD

**Issue by touwys** [htrinter/Open-Multiple-URLs#25]
Please add a **Total** for the number of URL's that are currently listed in Open Multiple URLs pane. This should help the user to improve his tab memory management. If, in addition, the user is allowed to select and choose any number of URLs he wished to load, it will certainly prove to be a bonus.

Thank you.

_Example screenshot:_

![image](https://user-images.githubusercontent.com/65730626/104304600-3d1c5900-54d4-11eb-85ff-dc08751ee8da.png)

**Comment by touwys** [comment]
Please, reconsider implementing this proposed feature by showing the number of tabs that's been added to the window. It will give the user a visual advance warning if the browser is about to be overloaded with tabs. 

Thank you.

**Comment by htrinter** [comment]
Hi touwy, I reopened the issue on your request. I guess it would be a cool feature ... the number of tabs would be the number of non-empty lines in the textbox. Care should be taken to not compromise performance, because the number would need to be calculated on text change.

**Comment by htrinter** [comment]
Implemented in v1.5.3
