### ISSUE TITLE
When in Incognito mode, "Don't load tabs until selected" checked makes extension open URLs in regular window, not Incognito

### ISSUE THREAD

**Issue by echernyavskiy** [htrinter/Open-Multiple-URLs#26]
When using this extension in Incognito mode, if "Don't load tabs until selected" is checked, URLs are opened NOT in Incognito mode.

**Comment by htrinter** [comment]
I am able to reproduce the issue in Chrome. Manifest option "incognito": "split" seems to fix the issue. Unfortunately it makes the extension manifest incompatible with Firefox. Seems like we need a separate build for Firefox.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito

**Comment by htrinter** [comment]
Fixed in v1.5.1
