### ISSUE TITLE
[Feature Request]  Possibly a few Preset buttons

### ISSUE THREAD

**Issue by XxPhoenixXx** [htrinter/Open-Multiple-URLs#28]
Wondering if its possible to add some Preset buttons or Playtlists as one reviewer mentioned

e.g.
We have a list of urls for opening News sites - Preset button 1
A list of Urls for video games - Preset button 2
a 3rd list for Sharks - Preset button 3.

Sorry not sure how to make this a real feature request

**Comment by htrinter** [comment]
Hi, I think this can be achieved with browser functionalities. For Firefox: 1) Open a list of URLs using the extension, 2) bookmark all tabs to a folder (https://support.mozilla.org/en-US/questions/1310974) 3) right click on folder, choose "Open All in Tabs".
