### ISSUE TITLE
Entension disappeared from Chrome Web Store

### ISSUE THREAD

**Issue by urShadoww** [htrinter/Open-Multiple-URLs#31]
The link to Chrome Web Store is returning an error, what happened?

https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh

![image](https://user-images.githubusercontent.com/19491462/115650242-8846d300-a331-11eb-8eb6-7427fac94a37.png)

**Comment by htrinter** [comment]
Google removed the extension from the store, without any clear reason 
communicated to me. I contacted them ... we'll see.

**Comment by urShadoww** [comment]
Thanks for your prompt response, can you plz guide how can I convert the .zip release file to crx to upload it manually in a browser?

**Comment by htrinter** [comment]
Please refer to the browser's documentation on how to load an unpacked extension. It's linked in the readme.

**Comment by htrinter** [comment]
Got a response from Google. Apparently "tabs" permission is not necessary for creating new tabs. I removed the permission in v1.5.2 and resubmitted. Approval in Chrome Web Store is pending.

**Comment by urShadoww** [comment]
Thanks for the update, looking forward to see the extension back in the store.

**Comment by jtagcat** [comment]
Their problem is too wide permissions. IIRC there are sub-permissions. But they are dicks in communicating, indeed.

**Comment by htrinter** [comment]
Google approved the new version. The extension is available again.

**Comment by urShadoww** [comment]
Thanks for the update.
