### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by fabulousrice** [htrinter/Open-Multiple-URLs#35]
It'd be great to easily access **_simple instructions_** on how to use the add-on.

For example if I click Tools > Add-ons, there's a description text there... but nothing that tells me how to use it. Same with this Github's Read Me...?!
Is there a hotkey to press to enable it? Obviously if I just left-mouse-button drag it will simply select text...

Very confused.

**Comment by htrinter** [comment]
Hi, there should be an icon in the browser's toolbar. Chrome hides extension icons by default now. You habe to "pin" it to the toolbar. Click the "Extensions" button in the toolbar to do that. Then click on the extension's icon, enter URLs and click the "open" button. Maybe documentation could be improved, given Chrome's new default behaviour.
