### ISSUE TITLE
Looking to talk with Dev/Creator about possible mods to the Open-Multiple-URLs extension

### ISSUE THREAD

**Issue by deehill** [htrinter/Open-Multiple-URLs#36]
Hi Hagen.

My Name is Bruce.

I'm looking for an extension that I can test/play with for testing URLs in multiple tabs. I'm looking to actually have an extension that would allow me to pull in different URLs from an external webserver, and run the urls in a group of tabs. Looking to work in FF/Chrome if possible.

There's more to what I'm ultimately looking for and I'm willing to discuss. All of this can be "open" with no problem there. 

I'm wondering if you might be interested in me paying a bit for what I'm looking for?

If you're interested, or if you know someone who might be interested, hit me up!

thanks

-bruce

**Comment by htrinter** [comment]
Hi, you are free of course to fork the project and develop it according to your needs. As for me: I am currently not available for freelance development work, thanks for the request.
