### ISSUE TITLE
[Feature Request] Delete loaded cookies after closing the tab

### ISSUE THREAD

**Issue by RomuloVianna** [htrinter/Open-Multiple-URLs#48]
My feature suggestion is to add an extra checkbox option "Delete loaded cookies after closing the tab". This feature in combination with the "Do not load tabs until selected" will allow to open the multiple tabs individually in unrelated instances if closing one before selecting the other.

**Comment by htrinter** [comment]
Hi, Thanks for the suggestion. I want to keep the extension small, lean and easily maintainable. Therefore I have no plans of adding more features at the moment. The extension is Open Source, so maybe somebody else or you yourself want to pick up the idea in a fork.
