### ISSUE TITLE
Add an option to open URLs in the reverse order (from bottom to top)

### ISSUE THREAD

**Issue by klint** [htrinter/Open-Multiple-URLs#49]
In my configuration, new tabs open in the reverse order compared to the input list of URLs : the last URL ends up in the first tab to the left, eventually.
May be this is a bug, or rather it is linked to the way new tabs opens on my Firefox config.
Could there be an option to reverse the order URLs are open ? (or the bug corrected if is is a bug ;) )
Thank you

**Comment by htrinter** [comment]
Implemented in v1.5.5
