### ISSUE TITLE
[Chrome] Activating the extension via Keyboard Shortcut broken

### ISSUE THREAD

**Issue by Bison700** [htrinter/Open-Multiple-URLs#54]
I recognized recently that the extension is missing in [chrome://extensions/shortcuts](url).

Thus the keyboard shortcut that I assigned to activate the extension does not work anymore. The behaviour is the same on other computers. It worked before so I guess it is not intended.

**Comment by htrinter** [comment]
That is probably down to the upgrade to manifest version 3. I will take a look.

**Comment by htrinter** [comment]
Fixed in v1.5.6 currently in Google's review process. Manifest v3 needs some additional configuration for shortcuts to be enabled, that I have now added.

**Comment by htrinter** [comment]
Fix is published on Chrome Web Store. Please note that Chrome may need a restart after setting the shortcut. Seems to be a known issue https://bugs.chromium.org/p/chromium/issues/detail?id=1190476
