### ISSUE TITLE
file:///path/to/file not supported

### ISSUE THREAD

**Issue by reikred** [htrinter/Open-Multiple-URLs#6]
I imagine I may not be the only one that might  want to open some files using the file:///path/to/file type of a URL? Should be an easy fix to add?

**Comment by jtagcat** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

It is not possible to open a file with any extension. Please open an issue upstream.

**Comment by htrinter** [comment]
As jtagcat said, the file scheme is not supported by the extension API. Therefore I'm closing the issue.
