### ISSUE TITLE
Please add previous chrome browser version support

### ISSUE THREAD

**Issue by browserwatchtg** [htrinter/Open-Multiple-URLs#67]
hello please add support for chrome://flags/#extensions-toolbar-menu compatible browsers, because it stopped to work on these and it works only on the new version with the shitty extension bar

![Image Copied on 2023-02-03 at 09 31 12 AM](https://user-images.githubusercontent.com/114294762/216551085-6fe29646-6072-4bd9-8e76-d18eb9b1a37d.jpeg)

**Comment by htrinter** [comment]
Hi , the extension is only compatible with Manifest Version 3. Version 2 is EOL and will stop working soon in Chrome.
