### ISSUE TITLE
How to open intranet-links?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [htrinter/Open-Multiple-URLs#71]
On my joomla-based intranet, this app finds links like
index.php/alle-kategorien/anleitungen/geraete-und-instrumente/plotter-scanner

If I want to open it, it fails - although the target exists. Is there a way to handle links of this style?

**Comment by htrinter** [comment]
Hi, the host has to be inclued in the URL. Like so: https://github.com/index.php/alle-kategorien/anleitungen/geraete-und-instrumente/plotter-scanner

A feature could be build that preprends a base URL. This is not planned however.
