### ISSUE TITLE
does not work in Arc browser?

### ISSUE THREAD

**Issue by tianyw0** [htrinter/Open-Multiple-URLs#93]
I migrate from chrome to arc, this plugin does not work.
what do I need to do?

**Comment by htrinter** [comment]
Hi, what exactly isn't working? Installs and shows up for me. Opening URLs works fine too.
<img width="324" alt="SCR-20241104-qfte" src="https://github.com/user-attachments/assets/3dba5b1d-bee0-46d7-9f5e-8f5b5d6c7203">
